/*
 * This file is generated by jOOQ.
 */
package com.genius.backend.domain.db;


import com.genius.backend.domain.db.tables.Alimy;
import com.genius.backend.domain.db.tables.AlimyUnits;
import com.genius.backend.domain.db.tables.Logs;
import com.genius.backend.domain.db.tables.Privilege;
import com.genius.backend.domain.db.tables.Roles;
import com.genius.backend.domain.db.tables.RolesPrivileges;
import com.genius.backend.domain.db.tables.Users;
import com.genius.backend.domain.db.tables.UsersRoles;
import com.genius.backend.domain.db.tables.UsersSocial;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Genius extends SchemaImpl {

    private static final long serialVersionUID = -440079056;

    /**
     * The reference instance of <code>genius</code>
     */
    public static final Genius GENIUS = new Genius();

    /**
     * The table <code>genius.alimy</code>.
     */
    public final Alimy ALIMY = com.genius.backend.domain.db.tables.Alimy.ALIMY;

    /**
     * The table <code>genius.alimy_units</code>.
     */
    public final AlimyUnits ALIMY_UNITS = com.genius.backend.domain.db.tables.AlimyUnits.ALIMY_UNITS;

    /**
     * The table <code>genius.logs</code>.
     */
    public final Logs LOGS = com.genius.backend.domain.db.tables.Logs.LOGS;

    /**
     * The table <code>genius.privilege</code>.
     */
    public final Privilege PRIVILEGE = com.genius.backend.domain.db.tables.Privilege.PRIVILEGE;

    /**
     * The table <code>genius.roles</code>.
     */
    public final Roles ROLES = com.genius.backend.domain.db.tables.Roles.ROLES;

    /**
     * The table <code>genius.roles_privileges</code>.
     */
    public final RolesPrivileges ROLES_PRIVILEGES = com.genius.backend.domain.db.tables.RolesPrivileges.ROLES_PRIVILEGES;

    /**
     * The table <code>genius.users</code>.
     */
    public final Users USERS = com.genius.backend.domain.db.tables.Users.USERS;

    /**
     * The table <code>genius.users_roles</code>.
     */
    public final UsersRoles USERS_ROLES = com.genius.backend.domain.db.tables.UsersRoles.USERS_ROLES;

    /**
     * The table <code>genius.users_social</code>.
     */
    public final UsersSocial USERS_SOCIAL = com.genius.backend.domain.db.tables.UsersSocial.USERS_SOCIAL;

    /**
     * No further instances allowed
     */
    private Genius() {
        super("genius", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Alimy.ALIMY,
            AlimyUnits.ALIMY_UNITS,
            Logs.LOGS,
            Privilege.PRIVILEGE,
            Roles.ROLES,
            RolesPrivileges.ROLES_PRIVILEGES,
            Users.USERS,
            UsersRoles.USERS_ROLES,
            UsersSocial.USERS_SOCIAL);
    }
}
