/*
 * This file is generated by jOOQ.
 */
package com.genius.backend.domain.db;


import com.genius.backend.domain.db.tables.Alimy;
import com.genius.backend.domain.db.tables.AlimyUnits;
import com.genius.backend.domain.db.tables.Logs;
import com.genius.backend.domain.db.tables.Privilege;
import com.genius.backend.domain.db.tables.Roles;
import com.genius.backend.domain.db.tables.RolesPrivileges;
import com.genius.backend.domain.db.tables.Users;
import com.genius.backend.domain.db.tables.UsersRoles;
import com.genius.backend.domain.db.tables.UsersSocial;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>genius</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ALIMY_PRIMARY = Indexes0.ALIMY_PRIMARY;
    public static final Index ALIMY_UNITS_ALIMY_UNIT_UNIQUE = Indexes0.ALIMY_UNITS_ALIMY_UNIT_UNIQUE;
    public static final Index ALIMY_UNITS_PRIMARY = Indexes0.ALIMY_UNITS_PRIMARY;
    public static final Index LOGS_PRIMARY = Indexes0.LOGS_PRIMARY;
    public static final Index PRIVILEGE_PRIMARY = Indexes0.PRIVILEGE_PRIMARY;
    public static final Index ROLES_PRIMARY = Indexes0.ROLES_PRIMARY;
    public static final Index ROLES_PRIVILEGES_PRIMARY = Indexes0.ROLES_PRIVILEGES_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_PROVIDER_UNIQUE = Indexes0.USERS_PROVIDER_UNIQUE;
    public static final Index USERS_ROLES_PRIMARY = Indexes0.USERS_ROLES_PRIMARY;
    public static final Index USERS_ROLES_USER_ID_USER_ID_UNIQUE = Indexes0.USERS_ROLES_USER_ID_USER_ID_UNIQUE;
    public static final Index USERS_SOCIAL_PRIMARY = Indexes0.USERS_SOCIAL_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ALIMY_PRIMARY = Internal.createIndex("PRIMARY", Alimy.ALIMY, new OrderField[] { Alimy.ALIMY.ID }, true);
        public static Index ALIMY_UNITS_ALIMY_UNIT_UNIQUE = Internal.createIndex("ALIMY_UNIT_UNIQUE", AlimyUnits.ALIMY_UNITS, new OrderField[] { AlimyUnits.ALIMY_UNITS.ALIMY_ID, AlimyUnits.ALIMY_UNITS.UNIT_TYPE }, true);
        public static Index ALIMY_UNITS_PRIMARY = Internal.createIndex("PRIMARY", AlimyUnits.ALIMY_UNITS, new OrderField[] { AlimyUnits.ALIMY_UNITS.ID }, true);
        public static Index LOGS_PRIMARY = Internal.createIndex("PRIMARY", Logs.LOGS, new OrderField[] { Logs.LOGS.ID }, true);
        public static Index PRIVILEGE_PRIMARY = Internal.createIndex("PRIMARY", Privilege.PRIVILEGE, new OrderField[] { Privilege.PRIVILEGE.ID }, true);
        public static Index ROLES_PRIMARY = Internal.createIndex("PRIMARY", Roles.ROLES, new OrderField[] { Roles.ROLES.ID }, true);
        public static Index ROLES_PRIVILEGES_PRIMARY = Internal.createIndex("PRIMARY", RolesPrivileges.ROLES_PRIVILEGES, new OrderField[] { RolesPrivileges.ROLES_PRIVILEGES.ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_PROVIDER_UNIQUE = Internal.createIndex("PROVIDER_UNIQUE", Users.USERS, new OrderField[] { Users.USERS.PROVIDER_TYPE, Users.USERS.PROVIDER_USER_ID }, true);
        public static Index USERS_ROLES_PRIMARY = Internal.createIndex("PRIMARY", UsersRoles.USERS_ROLES, new OrderField[] { UsersRoles.USERS_ROLES.ID }, true);
        public static Index USERS_ROLES_USER_ID_USER_ID_UNIQUE = Internal.createIndex("USER_ID_USER_ID_UNIQUE", UsersRoles.USERS_ROLES, new OrderField[] { UsersRoles.USERS_ROLES.USER_ID, UsersRoles.USERS_ROLES.ROLE_ID }, true);
        public static Index USERS_SOCIAL_PRIMARY = Internal.createIndex("PRIMARY", UsersSocial.USERS_SOCIAL, new OrderField[] { UsersSocial.USERS_SOCIAL.ID }, true);
    }
}
