/*
 * This file is generated by jOOQ.
 */
package com.genius.backend.domain.db;


import com.genius.backend.domain.db.tables.Alimy;
import com.genius.backend.domain.db.tables.AlimyUnits;
import com.genius.backend.domain.db.tables.Logs;
import com.genius.backend.domain.db.tables.Privilege;
import com.genius.backend.domain.db.tables.Roles;
import com.genius.backend.domain.db.tables.RolesPrivileges;
import com.genius.backend.domain.db.tables.Users;
import com.genius.backend.domain.db.tables.UsersRoles;
import com.genius.backend.domain.db.tables.UsersSocial;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in genius
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>genius.alimy</code>.
     */
    public static final Alimy ALIMY = com.genius.backend.domain.db.tables.Alimy.ALIMY;

    /**
     * The table <code>genius.alimy_units</code>.
     */
    public static final AlimyUnits ALIMY_UNITS = com.genius.backend.domain.db.tables.AlimyUnits.ALIMY_UNITS;

    /**
     * The table <code>genius.logs</code>.
     */
    public static final Logs LOGS = com.genius.backend.domain.db.tables.Logs.LOGS;

    /**
     * The table <code>genius.privilege</code>.
     */
    public static final Privilege PRIVILEGE = com.genius.backend.domain.db.tables.Privilege.PRIVILEGE;

    /**
     * The table <code>genius.roles</code>.
     */
    public static final Roles ROLES = com.genius.backend.domain.db.tables.Roles.ROLES;

    /**
     * The table <code>genius.roles_privileges</code>.
     */
    public static final RolesPrivileges ROLES_PRIVILEGES = com.genius.backend.domain.db.tables.RolesPrivileges.ROLES_PRIVILEGES;

    /**
     * The table <code>genius.users</code>.
     */
    public static final Users USERS = com.genius.backend.domain.db.tables.Users.USERS;

    /**
     * The table <code>genius.users_roles</code>.
     */
    public static final UsersRoles USERS_ROLES = com.genius.backend.domain.db.tables.UsersRoles.USERS_ROLES;

    /**
     * The table <code>genius.users_social</code>.
     */
    public static final UsersSocial USERS_SOCIAL = com.genius.backend.domain.db.tables.UsersSocial.USERS_SOCIAL;
}
