# default (production)
spring:
  http:
    log-request-details: true
  devtools:
    livereload:
      enabled: true
  resources:
    add-mappings: true
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: genius
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        globally_quoted_identifiers: true
        jdbc:
          fetch_size: 30
          batch_size: 30
    open-in-view: false

server:
  port: 9030
  undertow:
    accesslog:
      enabled: true
      dir: logs
      prefix: access.
    worker-threads: 10
  error:
    whitelabel:
      enabled: false

logging:
  file: logs/application.Log
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.genius.backend: DEBUG

management:
  endpoint:
    health:
      show-details: always

mybatis:
  type-aliases-package: com.genius.backend.domain.mapper
  type-handlers-package: com.genius.backend.domain.typehandler
  mapper-locations: classpath:/com/genius/backend/**/*.xml

genius:
  name: genius
  age: 39
  jwtSecret: genius
  jwtExpirationInMs: 604800000

ms:
  allowedOrigins: http://10.102.60.137:8080, http://35.247.88.70

info:
    app:
      name: Alimy
      version: 1.0.0

---

# office, default
spring:
  profiles: office, default

  social:
    kakao:
      appId: b84d72468acf74d7d892d55cb8e134ff
      appSecret: irWqNnhiBUfpC5Gjlc8bV8LmSphwLyM5
      accessTokenUrl: https://kauth.kakao.com/oauth/authorize
      userAuthorizationUrl: https://kauth.kakao.com/oauth/token
      scope: talk_message,profile
    line:
      appId: 1640532996
      appSecret: 1856fd835f2f93f9020060993b78c71a
      message:
        appId: 1640533899
        appSecret: 47f26a58a31e86fffe7039a002ff846c
        accessToken: FtKSVMr9BzL9r3Plpc2tzQxuhksWuf4eXXJegz3JED+UfLwRaWIy2O9DPYINWRlUwEX87JIwAn4rm1i2hho+cZUV1SeNxhxJ7m7YzCJehkxEO5c25Py6uv2ehVqcVxq7ajoWYV0nvWyWszGuzzbFJgdB04t89/1O/w1cDnyilFU=

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username : ${DATABASE_USERNAME}
      password : ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-master
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-slave

---

# real
spring:
  profiles: home

  social:
    kakao:
      appId: e471a3c9115dec82d061acd2a58be02b
      appSecret: https://kauth.kakao.com/oauth/authorize
      userAuthorizationUrl: https://kauth.kakao.com/oauth/token
      scope: talk_message,profile
    line:
      appId: 1640532996
      appSecret: 1856fd835f2f93f9020060993b78c71a

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://35.243.66.195:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-master
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://35.243.66.195:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-slave

---

# real
spring:
  profiles: real

  social:
    kakao:
      clientId: e471a3c9115dec82d061acd2a58be02b
      accessTokenUrl: https://kauth.kakao.com/oauth/authorize
      userAuthorizationUrl: https://kauth.kakao.com/oauth/token
      scope: talk_message,profile
    line:
      appId: 1640532996
      appSecret: 1856fd835f2f93f9020060993b78c71a

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-master
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/genius?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      connection-init-sql: SELECT 1 FROM DUAL
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
      connection-timeout: 60000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: wmp-genius-slave
