DROP TABLE IF EXISTS ALIMY;
DROP TABLE IF EXISTS ALIMY_UNITS;
DROP TABLE IF EXISTS PRIVILEGE;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS ROLES_PRIVILEGES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERS_ROLES;
DROP TABLE IF EXISTS USERS_SOCIAL;
DROP TABLE IF EXISTS LOGS;

CREATE TABLE ALIMY (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `STATUS` char(1) NOT NULL DEFAULT '1',
  `SUBJECT` varchar(100) NOT NULL,
  `MESSAGE` varchar(500) NOT NULL,
  `REG_DATETIME` datetime DEFAULT NULL,
  `MOD_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE ALIMY_UNITS (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ALIMY_ID` int(11) NOT NULL,
  `UNIT_TYPE` varchar(3) NOT NULL,
  `UNIT_VALUE` varchar(40) NOT NULL,
  `REG_DATETIME` datetime DEFAULT NULL,
  `MOD_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ALIMY_UNIT_UNIQUE` (`ALIMY_ID`,`UNIT_TYPE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRIVILEGE (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ROLES (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ROLES_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(11) NOT NULL,
  `PRIVILEGE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROVIDER_TYPE` varchar(20) NOT NULL,
  `PROVIDER_USER_ID` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) DEFAULT NULL,
  `USER_NAME` varchar(45) NOT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `IMAGE_URL` varchar(200) DEFAULT NULL,
  `REG_DATETIME` datetime DEFAULT NULL,
  `MOD_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PROVIDER_UNIQUE` (`PROVIDER_TYPE`,`PROVIDER_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USERS_ROLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID_USER_ID_UNIQUE` (`USER_ID`,`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `USERS_SOCIAL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ACCESS_TOKEN` varchar(250) DEFAULT NULL,
  `REFRESH_TOKEN` varchar(200) DEFAULT NULL,
  `SECRET` varchar(200) DEFAULT NULL,
  `PAGE_USER_ID` varchar(200) DEFAULT NULL,
  `PAGE_ACCESS_TOKEN` varchar(200) DEFAULT NULL,
  `MESSAGE_ACCESS_TOKEN` varchar(200) DEFAULT NULL,
  `EXPIRED_TIME` bigint(11) DEFAULT NULL,
  `REG_DATETIME` datetime DEFAULT NULL,
  `MOD_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LOGS (
  ID int PRIMARY KEY AUTO_INCREMENT,
  TYPE int NOT NULL,
  VALUE JSON,
  REG_DATETIME datetime DEFAULT NULL,
  MOD_DATETIME datetime DEFAULT NULL,
  CHECK (JSON_VALID(VALUE))
);

INSERT INTO ROLES VALUES (1, 'ADMIN'), (2, 'MANAGER'), (3, 'USER');